#########################
# roles/webserver/tasks
#########################

- name: Install packages
  apt: package={{ item }} state=present update_cache=yes
  with_items:
      - apache2
      - libapache2-mod-php5
      - php5-dev
      - php-pear
  tags: webserver
  notify:
    - restart apache

- name: Configure apache
  template: src=dayswithout.conf dest=/etc/apache2/sites-available/dayswithout.conf owner=root group=root mode=0644
  notify:
      - restart apache

- name: Enable configuration
  file: src=/etc/apache2/sites-available/dayswithout.conf dest=/etc/apache2/sites-enabled/dayswithout.conf state=link
  notify:
    - restart apache

- name: remove default apache configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart apache

- shell: pear config-set auto_discover 1

- name: update pear channels
  ignore_errors: yes
  shell: pear channel-discover {{ item }}
  with_items:
      - pear.symfony-project.com
      - components.ez.no
      - pear.symfony.com
  ignore_errors: yes

- name: update pear
  shell: pear upgrade pear

- name: Install pear packages
  shell: yes '' | pear install {{ item }}
  with_items:
      - pear.netpirates.net/Autoload
  ignore_errors: yes

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags: composer

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags: composer

- name: make composer executable
  shell: chmod a+x /usr/local/bin/composer
  tags: composer
  notify:
    - compose project

