#########################
# roles/webserver/tasks
#########################

- name: Install packages
  apt: package={{ item }} state=present update_cache=yes
  with_items:
      - apache2
      - libapache2-mod-php5
      - php5
  tags: webserver
  notify:
    - restart apache

- name: Configure apache
  template: src=dayswithout.conf dest=/etc/apache2/sites-available/dayswithout.conf owner=root group=root mode=0644
  notify:
      - restart apache

- name: Enable configuration
  file: src=/etc/apache2/sites-available/dayswithout.conf dest=/etc/apache2/sites-enabled/dayswithout.conf state=link
  notify:
    - restart apache

- name: remove default apache configuration
  file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart apache

- name: Enable mod-rewrite
  file: src=/etc/apache2/mods-available/rewrite.load dest=/etc/apache2/mods-enabled/rewrite.load state=link
  notify:
    - restart apache

- name: Log php-errors to syslog
  lineinfile: dest={{item}} regexp='^;?error_log = syslog' line='error_log = syslog' state=present
  with_items:
    - /etc/php5/apache2/php.ini
    - /etc/php5/cli/php.ini

- name: Ensure apache2 running
  service: name=apache2 state=started
