#########################
# appserver/tasks/main
#########################

- name: Create directory for dayswithout
  file: path=/opt/jsomerstone state=directory owner=root group={{apache_user}}

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer
  tags:
    - composer
    - app

- name: install deps
  apt: package=php-pear state=present
  tags: pear

- name: Enable pear auto-discover
  shell: pear config-set auto_discover 1
  tags: pear

- name: rename composer.phar to composer
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer
  tags:
      - composer
      - app

- name: make composer executable
  shell: chmod a+x /usr/local/bin/composer
  tags:
      - composer
      - app

- name: update pear channels
  shell: pear channel-discover {{ item }}
  register: channel_result
  changed_when: "'initialized' not in channel_result.stdout"
  failed_when: "'already initialized' not in channel_result.stdout"
  with_items:
      - pear.symfony-project.com
      - components.ez.no
      - pear.symfony.com
  tags: pear

- name: Install pear packages
  shell: yes '' | pear install {{ item }}
  register: packet_install
  changed_when: "'installed' not in packet_install.stdout"
  failed_when: "'already installed' not in packet_install.stdout"
  with_items:
      - pear.netpirates.net/Autoload

- name: compose project
  shell: composer install --working-dir {{application_path}} --optimize-autoloader
  args:
        creates: "{{application_path}}/vendor/autoload.php"
  tags:
    - composer
    - app

- name: Symlink to current version
  file:
    src="/opt/jsomerstone/dayswithout-{{version}}"
    dest=/opt/jsomerstone/dayswithout
    state=link
    owner={{owner}}
    group={{apache_user}}
  tags: app

- name: Symlink to document root
  file:
    src=/opt/jsomerstone/dayswithout/web
    dest=/var/www/html/dayswithout
    state=link
    owner={{owner}}
    group={{apache_user}}
  tags: app
