JSomerstone\DaysWithoutBundle\Model:
    properties:
        headline:
            - NotBlank: ~
        name:
            - NotBlank: ~
        owner:
            - Type: \JSomerstone\DaysWithoutBundle\Model\UserModel