imports:
    - { resource: config.yml }

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

j_somerstone_days_without:
    storage:
        # Absolute path to store Counters to
        counter_path: /tmp/dwo/prod/counters
        # Absolute path to store Users to
        user_path: /tmp/dwo/prod/users