#########################
# dev/tasks/main
#########################
- name: install deps
  apt: package={{item}} state=present update_cache=yes
  with_items:
    - php5-dev
    - php-pear
    - curl
    - git
    - npm
  tags: dev

- name: Copy motd
  template: src=motd dest=/etc/motd owner=root group=root mode=755
  tags: dev

- name: Change default dir
  lineinfile: dest=/home/vagrant/.bashrc
              line="cd /vagrant"
              state=present
  tags: dev

- name: update pear channels
  shell: pear channel-discover pear.phpunit.de
  ignore_errors: yes
  tags: dev

- name: Install pear packages
  shell: yes '' | pear install pear.phpunit.de/PHPUnit
  ignore_errors: yes
  register: pear_result
  changed_when: "'installed' not in pear_result.stdout"
#  failed_when: "'6.2.0.0' not in pear_result.stdout"
  tags: dev

- npm: name=qunitjs path=/vagrant/web/test

- name: create development directories
  file:
    path={{item}}
    state=directory
    owner={{owner}}
    group={{apache_user}}
    mode=775
  with_items:
    - /tmp/dwo/dev/
    - /tmp/dwo/dev/cache/
    - /tmp/dwo/dev/logs/
    - /tmp/dwo/test/
    - /tmp/dwo/test/cache/
    - /tmp/dwo/test/logs/

- name: Warmup cache
  shell: "{{application_path}}/app/console cache:clear --env={{env}} --no-debug"
  tags: dev

- name: enable cache
  file:
    path=/tmp/dwo/dev/cache/
    state=directory
    recurse=yes
    owner={{owner}}
    group={{apache_user}}
    mode=775
  tags: dev

- name: Symlink sources to production path
  file:
      src={{application_path}}
      dest=/opt/jsomerstone/dayswithout-{{version}}
      state=link
      owner={{owner}}
      group={{apache_user}}
