#########################
# dev/tasks/main
#########################
- name: install deps
  apt: package={{item}} state=present update_cache=yes
  with_items:
    - php5-dev
    - php-pear
    - curl
    - git
    - npm
  tags: dev

- name: Copy motd
  template: src=motd dest=/etc/motd owner=root group=root mode=755
  tags: dev

- name: Change default dir
  lineinfile: dest=/home/vagrant/.bashrc
              line="cd /vagrant"
              state=present
  tags: dev

- name: Download PHPUnit
  shell: curl -sS https://phar.phpunit.de/phpunit.phar > /usr/local/bin/phpunit creates=/usr/local/bin/phpunit

- name: Make PHPUnit executable
  file: path=/usr/local/bin/phpunit owner={{owner}} mode=0755

#- npm: name=qunitjs path=/vagrant/web/test

- name: Symlink sources to production path
  file:
      src={{application_path}}
      dest=/opt/jsomerstone/dayswithout-{{version}}
      state=link
      owner={{owner}}
      group={{apache_user}}
