#########################
# roles/php-mongo/tasks/main
#########################

---
- name: install deps
  apt: package={{item}} state=present
  with_items:
  - mongodb
  - gcc
  - php5-dev
  - php-pear
  tags: mongo-php

- name: set pecl php.ini location
  shell: pecl config-set php_ini /etc/php.ini
  tags: mongo-php

- name: determine php extensions directory
  shell: php -i | grep -i '^extension_dir' | awk '{print $3}'
  register: php_extension_dir
  tags: mongo-php

- name: install MongoClient for php
  shell: printf "\n" | pecl install mongo creates={{php_extension_dir.stdout_lines[0]}}/mongo.so
  tags: mongo-php

- name: make mongo.so executable
  file: path={{php_extension_dir.stdout_lines[0]}}/mongo.so mode=0755
  tags: mongo-php

- name: add mongo extension to php.ini configuration
  lineinfile: dest={{item}}
              line="extension=mongo.so"
              state=present
  with_items:
      - /etc/php5/apache2/php.ini
      - /etc/php5/cli/php.ini
  tags: mongo-php

- name: Ensure requested services are on
  service: name=mongodb state=started
  tags: mongo-php
