dwo_frontpage:
    pattern: /
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Default:index}

dwo_create_counter:
    pattern: /create
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:create }
    methods: [POST]

dwo_loginpage:
    pattern: /login
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:loginPage }
    methods: [GET]

dwo_login:
    pattern: /login
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:login }
    methods: [POST]

dwo_logout:
    pattern: /logout
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:logout }
    methods: [GET]

dwo_show_counter:
    pattern: /{name}/{owner}
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:show, owner: null }
    methods: [GET]

dwo_reset_counter:
    pattern: /{name}/{owner}
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:reset, owner: null }
    methods: [POST]
