dwo_frontpage:
    pattern: /
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Default:index}

dwo_create_counter:
    pattern: /create
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:create }
    methods: [POST]

dwo_loginpage:
    pattern: /login
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:loginPage }
    methods: [GET]

dwo_login:
    pattern: /login
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:login }
    methods: [POST]

dwo_logout:
    pattern: /logout
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:logout }
    methods: [GET]

dwo_signup_page:
    pattern: /signup
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:signupPage }
    methods: [GET]

dwo_signup:
    pattern: /signup
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Session:signup }
    methods: [POST]

dwo_list_user_counters:
    pattern: /user/{user}/counters
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:showUsersCounters }
    methods: [GET]

dwo_show_counter:
    pattern: /{name}/{owner}
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:show, owner: null }
    methods: [GET]

dwo_reset_counter:
    pattern: /{name}/{owner}
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:reset, owner: null }
    methods: [POST]

dwo_delete_counter:
    pattern: /api/counter/delete/{name}/{owner}
    defaults: { _controller: JSomerstoneDaysWithoutBundle:Counter:delete, owner: null }
    methods: [POST]

api_reset_couner:
  pattern: /api/counter/reset/{counter}/{owner}
  methods: [POST]
  defaults: { _controller: JSomerstoneDaysWithoutBundle:Api:reset, owner: null }

