parameters:
    dayswithout.storage.counter.class: JSomerstone\DaysWithoutBundle\Storage\CounterStorage
    dayswithout.storage.user.class: JSomerstone\DaysWithoutBundle\Storage\UserStorage
services:
    mongo_client:
      class: MongoClient
      arguments: [ %storage.server% ]
    dayswithout.storage.counter:
        class: %dayswithout.storage.counter.class%
        arguments: ["@mongo_client", %storage.database% ]
    dayswithout.storage.user:
        class: %dayswithout.storage.user.class%
        arguments: ["@mongo_client", %storage.database% ]

    dayswithout.service.authentication:
        class: JSomerstone\DaysWithoutBundle\Service\AuthenticationService
        arguments: [ @dayswithout.storage.user ]

