parameters:
    dayswithout.storage.counter.class: JSomerstone\DaysWithoutBundle\Storage\CounterStorage

services:
    dayswithout.storage.counter:
        class: %dayswithout.storage.counter.class%
        arguments: [%dayswithout.counter_path%]

