---
# This playbook deploys the whole application stack in this site.

- name: Setup PRODUCTION environment
  hosts: production
  vars:
      directory_index: app.php
      document_root: /var/www/html/dayswithout/
      version: 2.2.3
      application_path: "/opt/jsomerstone/dayswithout-{{version}}"
      env: prod
      owner: root
      apache_user: www-data
  roles:
    - common
    - webserver
    - php-mongo
    - prod
    - appserver
