#########################
# prod/tasks/main
#########################

- name: Clone app
  git: repo=https://github.com/JSomerstone/DaysWithoutX.git
       dest={{application_path}}
       version=v{{version}}
  tags: app
  notify: compose project

